#cloud-config

timezone: "UTC"

hostname: "<CHANGEME>"
fqdn: "<CHANGEME>"

package_update: true
package_upgrade: true
package_reboot_if_required: true

system_info:
  default_user:
    name: "patron"
    lock_passwd: true
    gecos: "Teloshost Patron"

users:
  - "default"

ssh_import_id:
  - <CHANGEME>
  - <CHANGEME>

write_files:
  - path: "/var/log/teloshost.yaml"
    content: |
      -   message: cloud-init enabled
          source: cloud-init
