## Purpose: Epilogue
## Idempotent: No, updates `teloshost__logfile`.

- name: Add a line to the end of the log file
  become: true
  ansible.builtin.lineinfile:
    path: "{{ teloshost__logfile }}"
    insertafter: EOF
    state: present
    line: "{{ [entry] | to_nice_yaml }}"
  vars:
    entry:
      timestamp: "{{ ansible_date_time.iso8601 }}"
      source: ansible
      message: finished
      version: "{{ teloshost__version }}"
