- name: Setup Backup Machine
  hosts: all
  tasks:
    - name: Install rclone
      ansible.builtin.shell: |
        set -o pipefail
        curl https://rclone.org/install.sh | sudo bash
      args:
        creates: /usr/bin/rclone

    - name: Install rrclone
      become: true
      become_method: sudo
      ansible.builtin.get_url:
        url: "https://github.com/telostat/rrclone/releases/latest/download/rrclone-{{ ansible_facts['system'] }}-{{ ansible_facts['architecture'] }}"
        dest: /usr/local/bin/rrclone
        mode: "755"

    - name: Install required packages
      become: true
      become_method: sudo
      ansible.builtin.apt:
        name: "{{ packages }}"
      vars:
        packages:
          - cryptsetup
          - restic
